### ISSUE TITLE
wiki for use in meetings 

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Landscape#17]
use Github or similar for a weekly agenda

**Comment by sarob** [comment]
I typically use light-weight GitHub wiki or etherpad https://github.com/ether/etherpad-lite/wiki/Sites-That-Run-Etherpad along with Miro for story boards. 

GitHub wiki home

# Overview

- [Overview](https://foo.bar/)
- [Project](/org/repo)
- [Work in Progress as a whiteboard](https://miro.com/app/board/blah blah)

_Sidebar

- [home](https://github.com/org/repo/wiki)
- [Meeting 04 Nov 2022](https://github.com/org/repo/wiki/meeting-04nov2022/_edit)
- [Meeting 28 Oct 2022](...

**Comment by epowell101** [comment]
thank you @sarob !  We started using the wiki this week!

**Comment by sarob** [comment]
Woot!Sean ***@***.*** On Nov 29, 2022, at 19:06, Evan Powell ***@***.***> wrote:﻿
thank you @sarob !  We started using the wiki this week!
