### ISSUE TITLE
Defining Mission / Vision / Values

### ISSUE THREAD

**Issue by Curi0usRabbit** [OpenDataforWeb3/Landscape#19]
Hey Friends, 

The mission, vision and values is our reason for being together. Right now, all i know is "opendata good, recentralization of data bad". lets get clearer on why we are coming together. ANY organization, especially decentralized/open, without this bedrock, is much more likely to dissipate

Mission -> What's the problem we're solving? Why are we here?

Vision -> What's the future of the world look like where we are successful?

Values -> The things we are unwilling to compromise on and drive us forward

Feel free to redefine these 3 categories, im sure there are better questions to prime better answers

**Comment by sarob** [comment]
I'll try from what I understand:
- Fight decentralization 
- Duplicate an organization similar to CNCF for broad adoption and acceptance 
- Outsource Gitcoin project governance

**Comment by epowell101** [comment]
Hey all - the way I see it the overall mission is to help protect web3 and crypto.

There are two main aspects to this today:
1.  Sybil resistance via data science and other approaches
2.  Resisting recentralization at the data layer

IMO resisting recentralization or supporting decentralized data layer solutions is our bedrock - however without #1 there might not be a locus of effort to rally.  

Also we are primarily supported today by Gitcoin which is at the forefront of efforts to resist Sybil attacks both via software via [Passport ](https://passport.gitcoin.co/) and of course via the efforts of the FDD team within Gitcoin.  If we collectively do not resist Sybil attacks then one of the real bright spots of web3 - the collective funding of public goods - would be captured by essentially criminal forces.  

I hope we keep this conversation going.  Maybe we should articulate as well some of our values which to me have to do with how we would want ourselves to behave with each other and the broader community.  My sense is that we want to highlight values such as:

- openness - working in public and actively requesting input
- candor - being direct and facts based 
- inclusive - making a particular effort to welcome and invite a breadth of perspectives
- initiative - last but definitely not least IMO - perhaps we should emphasize the importance of taking initiative

**Comment by sarob** [comment]
Default org README and new contributing docs published. Let call this closed for now and revisit for code of conduct.
