### ISSUE TITLE
Create Anti-Sybil whitepaper or landscape

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Landscape#20]
We can build off of the recent OpenData Hackathon write-up

Likely this should be its own landscape and area of emphasis

**Comment by Kishoraditya** [comment]
I can help out!
What do you think can be a starting point - based on gitcoin's journey, or should we try to include it overall web3 (and dfferene from web2)
Also - any fixation on where do we want it to be published?

**Comment by epowell101** [comment]
hi @Kishoraditya - the landscape here in the readme can be a good place to start afaik
what projects are missing in the landscape in your opinion?  please add either directly via a PR or suggest additions via an issue

**Comment by sarob** [comment]
> I can help out!
> 
> What do you think can be a starting point - based on gitcoin's journey, or should we try to include it overall web3 (and dfferene from web2)
> 
> Also - any fixation on where do we want it to be published?

Looks like https://github.com/OpenDataforWeb3/Landscape/issues/24 is also working on at least part of this. Please collaborate for maximum happiness!

**Comment by sarob** [comment]
I will close this in favor of duplicate #24
