### ISSUE TITLE
Adding a little structure to the ODC? 

### ISSUE THREAD

**Issue by Razga** [OpenDataforWeb3/Landscape#28]
Would it help if we created an accountabilla buddy circle and keep track of each others tasks for the moment? For example if I commit to writting an article in two weeks @epowell101 @poupou-web3 would keep be accountable for that and I would be one of the two people that would keep them accountable. Just an idea 👯

**Comment by sarob** [comment]
I think for the near future, we are going to try using github project, review in the weekly meeting, and experiment with dework. 
We can come back to this option if these other approaches don't work out. 
I will close this for now. Let us know if this makes sense to you or if you want to discuss further.
