### ISSUE TITLE
Check Pokt Endpoint

### ISSUE THREAD

**Issue by stefi-says** [OpenDataforWeb3/Landscape#47]
We are having problems in using pockt to get transactional data by address in ethereum network. Our concern is that hackathon contestants may need this data to perform network analysis ( probably using Raphtory, other sponsor of us) . We couldn't find an endpoint on their API that could bring this information. Here's the link for their documentation: 

https://docs.pokt.network/api-docs/ethereum/#/api-docs/ethereum/operations/eth_signTransaction

**Comment by stefi-says** [comment]
Through help of @poupou-web3 , @baokiddy and pokt collegues we figured out that Pockt uses  ethereum RPC methods https://ethereum.github.io/execution-apis/api-documentation/ . Therefore there is no endpoint that provides transactions indexed by wallet address. 
Next step is study Convalent, an unified API and its endpoints to come up with python scripts to data analyst , so they can query transactional data.

**Comment by poupou-web3** [comment]
Adding a link to the discord conversation even if the issue is closed to remember that it is possible to use TrueBlock and Pocket to index transactions https://discord.com/channels/1037443230993743902/1048288174805352530/1059099346894852126
