### ISSUE TITLE
Create simple website for ODC

### ISSUE THREAD

**Issue by epowell101** [OpenDataforWeb3/Landscape#6]
See who wants to help; build simple web site listing the proposed programs

**Comment by epowell101** [comment]
This web site can be similar to the TrueBlocks web site:  [](https://trueblocks.io/)
a) extremely simple - 1 page 
b) Hugo or similar static site that can be easily updated by the community

We want to have a blog that includes the ability to embed video.
Other top-level navigation includes:  Github, Discord

The primary content on the page should be easy to change.  We want one section summarizing our mission.  We can then have two columns - one articulating the benefits to community members and one articulating the benefits to developers.

**Comment by SpaceTristan** [comment]
I created something very basic website you can find here: 

https://github.com/SpaceTristan/open-data-website

I have a github pages deployed version here:
https://spacetristan.github.io/opendataforweb3.github.io/

But there is currently in issue when clicking into the posts. I will troubleshoot more tomorrow night but it may be due to naming or some issue with the template I am using when I generate the static files

Here is an example of what a blog post looks like:

![image](https://user-images.githubusercontent.com/29065567/206359528-7e68f81d-1a15-4bbe-9889-7b5af94371f4.png)

**Comment by sarob** [comment]
The path has an extra variable 
- Should be https://spacetristan.github.io/posts/mission/index.html
- right now is https://spacetristan.github.io/opendataforweb3.github.io/posts/mission/index.html

**Comment by SpaceTristan** [comment]
Yeah that was what I was thinking. I was thinking when the website is hosted from this organization then the name would be "opendataforweb3.github.io" hence the name. But for the current development I will change.

**Comment by SpaceTristan** [comment]
Site is up and working here: https://spacetristan.github.io/

**Comment by sarob** [comment]
Working site is published at https://opendataforweb3.github.io/Landscape/

@epowell101 It needs some marketing advice / direction on content and formatting. I will bring up in the next meeting.

**Comment by sarob** [comment]
@SpaceTristan I spoke with @epowell101 and he okayed creating a new repository so we can publish to opendataforweb3.github.io

I will setup shortly.

**Comment by SpaceTristan** [comment]
Sounds good @sarob . It sounds like we may want to look at some different templates also, I can mock up a few options and maybe we can run through them all on Tuesdays stand up with everyone.

**Comment by Curi0usRabbit** [comment]
whats up friends, im catching up on things in the discord. am thinking of making this into a notion page. could serve as our website for now. looking at the links here i notice they are not working

**Comment by SpaceTristan** [comment]
> Whats up friends, im catching up on things in the discord. 
> 
> am thinking of making a notion page to organize my own thoughts, could serve as an extra landing page for us as well. I notice the links above no longer work, let me know when its up again!


Hey the current url is the following and we are in the process of adding a custom url:

https://opendataforweb3.github.io/


And the working repo for the website is:

https://github.com/OpenDataforWeb3/opendataforweb3.github.io

**Comment by sarob** [comment]
@SpaceTristan is adding the https://getdoks.org/ theme shortly. this issue will be ready to be closed after that!

**Comment by sarob** [comment]
PR https://github.com/OpenDataforWeb3/opendataforweb3.github.io/pull/7 is merged. closing.
